travis:
  secure:
    BINSTAR_TOKEN: eJLk5QZGOy1IcdkncnaXotv1wS1ksSnV5ZRNBWv+iGvZmzIUdzSwO08z9/IJ9t0/PpzO/C9U3yrYh0HlR2xz1Qt1QwC0FTPG/sGNp1F6wsAPvsm30ssHC9ZlVYE0tW6R1znKekYguHrPOTZmZAfz72PmxbpX++xharivv7upecKbChuldUl8xnDB/yct6rGZzs/r4OGBF3elax2m75PbOtm2KEfyusjKjSIgd2+dLAS2yHP1W/ncri6oO+Fzqdr8nW0+40yqsJAw/Lo+qUKwQbpCms4ZlG+snsOw7P3fd/suWJP888egzlItHegjlUUtbJ1Vuop9FXP4YH594iOJLno6Mj3mlJVhTb+H/+7trnj/daTevdNdmYxfoMwsdZxT2KBVX5RtLe+RZ/bb9JjYPlwAmAE8L0xNWRQWo1JBzFXaejE9B3y/mBHhXQ/knGl9izpSLNaj/zyVpVeBFNh7x/HiRUW2x6EKxEnLB+nlx6ZG2kPGAiuxJjsBePsPO4GGrg7G7q6ImWnw18RmlrdTaIYvi7RlMSzh/NB3HMZQmt0ERgHGMyoJrki6lyFVDctl3dymNuLlxScUIrJaS97n5RWo66V7hbIm3pxVoDBIomv98ny4UJvHE2ML4Q2md2UHglwmeqz8ZgCjgxudS7CWFznEUv3ID6m6MOcTC0LmsOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
